### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by RykerCohen** [Adamb2019/No-Name-Source#2]
Hi. What are your plans for this? HAve any updates on discord or something?

**Comment by RykerCohen** [comment]
As well, where do i put my media server for testing

**Comment by Adamb2019** [comment]
media server would go inside ur htdocs and no i dont post updates

**Comment by RykerCohen** [comment]
and how do i get to the login?

**Comment by Adamb2019** [comment]
add my discord adamb#1917
